use jaali_clow::locator::{Locator2D, ParticleAdvector2D};
use jaali_clow::mesh::TriMesh;
use std::io::Write;

// ------------------------------------------------------------
// CLI
// ------------------------------------------------------------

struct Args {
    steps:         usize,
    out_every:     usize,
    dt:            f64,
    /// Particles per body-width in each direction — controls grid density.
    /// Overridden by --spacing if provided.
    ppc:           usize,
    /// Direct grid spacing in mesh units. Overrides --ppc when set.
    spacing:       Option<f64>,
    /// Particle x margin: body-widths in front of the body to fill with particles.
    x_margin:      f64,
    /// Particle y margin: body-heights above/below the body to fill with particles.
    y_margin:      f64,
    /// Mesh x margin: body-widths to extend the mesh beyond the particle region (each side).
    mesh_x_margin: f64,
    /// Mesh y margin: body-heights to extend the mesh beyond the particle region (each side).
    mesh_y_margin: f64,
}

fn parse_args() -> Args {
    let raw: Vec<String> = std::env::args().collect();
    let mut steps         = 100usize;
    let mut out_every     = 10usize;
    let mut dt            = 0.1f64;
    let mut ppc           = 5usize;
    let mut spacing       = None::<f64>;
    let mut x_margin      = 3.0f64;
    let mut y_margin      = 2.0f64;
    let mut mesh_x_margin = 1.0f64;
    let mut mesh_y_margin = 1.0f64;
    let mut i = 1;
    while i < raw.len() {
        match raw[i].as_str() {
            "--help" | "-h" => {
                println!("\
acoustic_particle_trapping_2d — acoustic streaming particle trapper

USAGE:
  cargo run --example acoustic_particle_trapping_2d -- [OPTIONS]

SIMULATION
  --steps N          Number of time steps to run            (default: 100)
  --out-every N      Write a VTK snapshot every N steps     (default: 10)
  --dt F             Time step size                         (default: 0.1)

PARTICLE GRID  (placed in front of the body, upstream)
  --ppc N            Particles per body-width in each direction.
                     Controls grid density via spacing = body_width / ppc.
                     Ignored if --spacing is given.          (default: 5)
  --spacing F        Grid spacing in mesh units (overrides --ppc).
                     Smaller = more particles.               (default: unset)
  --x-margin F       Particle region width in front of body,
                     expressed as multiples of body_width.   (default: 3.0)
  --y-margin F       Particle region height above/below body,
                     expressed as multiples of body_height.  (default: 2.0)

MESH  (sub-region written to vtk_out/acoustic_mesh_under_study.vtk)
  --mesh-x-margin F  Extra mesh beyond particle region in x,
                     expressed as multiples of body_width.   (default: 1.0)
  --mesh-y-margin F  Extra mesh beyond particle region in y,
                     expressed as multiples of body_height.  (default: 1.0)

OUTPUT
  VTK files are written to vtk_out/:
    acoustic_mesh_under_study.vtk   — sub-mesh around the body (static)
    particles_NNNNNN.vtk            — particle snapshots per --out-every

EXAMPLE
  cargo run --example acoustic_particle_trapping_2d -- \\
    --steps 5000 --out-every 50 --dt 1.0 \\
    --spacing 2.0 --x-margin 4 --y-margin 3 \\
    --mesh-x-margin 2 --mesh-y-margin 2
");
                std::process::exit(0);
            }
            "--steps"         => { steps         = raw[i+1].parse().unwrap(); i += 2; }
            "--out-every"     => { out_every      = raw[i+1].parse().unwrap(); i += 2; }
            "--dt"            => { dt             = raw[i+1].parse().unwrap(); i += 2; }
            "--ppc"           => { ppc            = raw[i+1].parse().unwrap(); i += 2; }
            "--spacing"       => { spacing        = Some(raw[i+1].parse().unwrap()); i += 2; }
            "--x-margin"      => { x_margin       = raw[i+1].parse().unwrap(); i += 2; }
            "--y-margin"      => { y_margin       = raw[i+1].parse().unwrap(); i += 2; }
            "--mesh-x-margin" => { mesh_x_margin  = raw[i+1].parse().unwrap(); i += 2; }
            "--mesh-y-margin" => { mesh_y_margin  = raw[i+1].parse().unwrap(); i += 2; }
            other => { eprintln!("unknown option: {other}  (try --help)"); i += 1; }
        }
    }
    Args { steps, out_every, dt, ppc, spacing, x_margin, y_margin, mesh_x_margin, mesh_y_margin }
}

// ------------------------------------------------------------
// ParaView visualisation script generator
// ------------------------------------------------------------

fn write_visualize_py(out_dir: &str, field_vtk_rel: &str, n_particles: usize) {
    let path = format!("{}/visualize.py", out_dir);
    let mut f = std::fs::File::create(&path).unwrap();

    write!(f, r#"# Auto-generated by jaali_clow::examples::acoustic_particle_trapping_2d
# Run from the "{out_dir}" directory:
#   pvpython visualize.py
#
# Simulation: Acoustic 2D — {n_particles} particles

from paraview.simple import *
import glob, re

paraview.simple._DisableFirstRenderCameraReset()

_SIM = "Acoustic 2D — {n_particles} particles"

# ── Background acoustic field ────────────────────────────────
field_reader = LegacyVTKReader(
    registrationName='acoustic_field',
    FileNames=['{field_vtk_rel}'])
field_reader.UpdatePipeline()

view = GetActiveViewOrCreate('RenderView')

field_disp = Show(field_reader, view, 'UnstructuredGridRepresentation')
field_disp.SetRepresentationType('Surface')
ColorBy(field_disp, ('CELLS', 'velocity'))
lut_field = GetColorTransferFunction('velocity')
lut_field.VectorMode = 'Magnitude'
field_disp.RescaleTransferFunctionToDataRange(False, True)
lut_field.ApplyPreset('Cool to Warm', True)
field_disp.SetScalarBarVisibility(view, True)

bar_field = GetScalarBar(lut_field, view)
bar_field.Orientation        = 'Horizontal'
bar_field.WindowLocation     = 'Any Location'
bar_field.Position           = [0.25, 0.18]
bar_field.ScalarBarLength    = 0.50
bar_field.ScalarBarThickness = 16
bar_field.Title              = 'velocity magnitude'

# ── Velocity vectors (arrows) ────────────────────────────────
# Cell data → point data so Glyph can use it
c2p = CellDatatoPointData(registrationName='c2p', Input=field_reader)
c2p.ProcessAllArrays = 1
c2p.UpdatePipeline()

glyph = Glyph(registrationName='vel_arrows', Input=c2p, GlyphType='Arrow')
glyph.OrientationArray  = ['POINTS', 'velocity']
glyph.ScaleArray        = ['POINTS', 'velocity']
glyph.ScaleFactor       = 1.0          # tune in ParaView if arrows are too big/small
glyph.GlyphMode         = 'Every Nth Point'
glyph.Stride            = 20           # show every 20th point to avoid clutter
glyph.UpdatePipeline()

glyph_disp = Show(glyph, view, 'GeometryRepresentation')
ColorBy(glyph_disp, ('POINTS', 'velocity'))
lut_g = GetColorTransferFunction('velocity')
lut_g.VectorMode = 'Magnitude'
glyph_disp.RescaleTransferFunctionToDataRange(False, True)
glyph_disp.SetScalarBarVisibility(view, False)

# ── Particle animation ───────────────────────────────────────
p_files = sorted(
    glob.glob('particles_*.vtk'),
    key=lambda f: int(re.search(r'\d+', f).group()))
if not p_files:
    raise RuntimeError(
        'No particles_*.vtk found. Run the simulation first, '
        'then launch pvpython from the vtk_out directory.')
print(f'[{{_SIM}}] {{len(p_files)}} timestep(s): {{p_files[0]}} ... {{p_files[-1]}}')

p_reader = LegacyVTKReader(registrationName='particles', FileNames=p_files)
p_reader.UpdatePipeline()

GetAnimationScene().UpdateAnimationUsingDataTimeSteps()

p_disp = Show(p_reader, view, 'UnstructuredGridRepresentation')
p_disp.SetRepresentationType('Point Gaussian')
p_disp.GaussianRadius   = 2.0
p_disp.ScaleByArray     = 0
p_disp.UseScaleFunction = 0
ColorBy(p_disp, ('POINTS', 'pressure'))
lut_p = GetColorTransferFunction('pressure')
p_disp.RescaleTransferFunctionToDataRangeOverTime()
lut_p.ApplyPreset('Plasma (matplotlib)', True)
p_disp.SetScalarBarVisibility(view, True)

bar_p = GetScalarBar(lut_p, view)
bar_p.Orientation        = 'Horizontal'
bar_p.WindowLocation     = 'Any Location'
bar_p.Position           = [0.25, 0.02]
bar_p.ScalarBarLength    = 0.50
bar_p.ScalarBarThickness = 16
bar_p.Title              = 'pressure (particles)'

# ── Camera — look down Z at the 2-D plane ────────────────────
_b  = field_reader.GetDataInformation().GetBounds()
_cx = 0.5 * (_b[0] + _b[1])
_cy = 0.5 * (_b[2] + _b[3])
_sp = max(_b[1] - _b[0], _b[3] - _b[2]) * 0.75

view.CameraPosition   = [_cx, _cy, _sp * 3.0]
view.CameraFocalPoint = [_cx, _cy, 0.0]
view.CameraViewUp     = [0.0, 1.0, 0.0]
view.ResetCamera()
Render()
print(f'[{{_SIM}}] visualization ready.')
"#,
        out_dir = out_dir,
        field_vtk_rel = field_vtk_rel,
        n_particles = n_particles,
    ).unwrap();

    println!("wrote {}", path);
}

// ------------------------------------------------------------
// ParaView reload macro generator
// ------------------------------------------------------------

fn write_reload_macro_py(out_dir: &str) {
    let path = format!("{}/reload_macro.py", out_dir);
    let mut f = std::fs::File::create(&path).unwrap();

    write!(f, r#""""
jaali_clow — ParaView reload macro
====================================

Add this file as a ParaView macro once:
    Tools > Macros > Add New Macro > (select this file)

Then trigger it whenever you want to pick up newly written VTK files:
    Macros > reload_macro          (menu)
    Tools > Keyboard Shortcuts     (assign a key, ParaView 5.12+)

What it does
------------
1. Finds every LegacyVTKReader currently loaded in the pipeline.
2. Derives the glob pattern from the first file in each reader's list
   (e.g. particles_000000.vtk → particles_*.vtk).
3. Re-scans the same directory, sorts numerically, skips empty/corrupt
   files, and updates each reader.
4. Refreshes the animation timeline and re-renders.
""""

from paraview.simple import *
import glob, os, re

# ── Reader XML names for legacy VTK across ParaView versions ─
_VTK_READER_NAMES = {{
    'LegacyVTKReader',
    'PVLegacyVTKFileReader',
    'legacyVTKReader',
}}

_SIM = "jaali_clow Stokes 2D"


def _is_vtk_reader(proxy):
    if proxy.GetXMLName() in _VTK_READER_NAMES:
        return True
    try:
        files = list(proxy.FileNames)
        return bool(files) and files[0].endswith('.vtk')
    except Exception:
        return False


def _is_valid_vtk(filepath):
    """Reject zero-byte or missing files."""
    try:
        return os.path.getsize(filepath) > 0
    except OSError:
        return False


def _sorted_valid_vtk(pattern):
    files = glob.glob(pattern)
    files.sort(key=lambda f: int(re.search(r'\d+', os.path.basename(f)).group()))
    valid = []
    for fp in files:
        if _is_valid_vtk(fp):
            valid.append(fp)
        else:
            print(f'[{{_SIM}}] WARNING: skipping empty/corrupt file {{fp}}')
    return valid


def _make_pattern(filepath):
    """
    Derive an absolute glob pattern from one existing file path.
    particles_000000.vtk  →  <dir>/particles_*.vtk
    """
    abspath   = os.path.abspath(filepath)
    directory = os.path.dirname(abspath)
    basename  = os.path.basename(abspath)
    m = re.match(r'^(.*?)_\d+\.vtk$', basename)
    if m is None:
        return None
    return os.path.join(directory, f'{{m.group(1)}}_*.vtk')


try:
    sources = GetSources()
    if not sources:
        print(f'[{{_SIM}}] Pipeline is empty — run visualize.py first '
              '(File > Run Script or Tools > Python Shell).')
    else:
        print(f'[{{_SIM}}] Pipeline has {{len(sources)}} source(s):')
        for (name, _), proxy in sources.items():
            print(f'          {{name!r}}  XML={{proxy.GetXMLName()!r}}')

    reloaded = 0

    for proxy in sources.values():
        if not _is_vtk_reader(proxy):
            continue

        try:
            current_files = list(proxy.FileNames)
        except Exception:
            continue

        if not current_files:
            continue

        pattern = _make_pattern(current_files[0])
        if pattern is None:
            print(f'[{{_SIM}}] Cannot derive pattern from {{current_files[0]!r}} — skipping.')
            continue

        print(f'[{{_SIM}}] Scanning: {{pattern}}')
        new_files = _sorted_valid_vtk(pattern)

        if not new_files:
            print(f'[{{_SIM}}] No files matched — skipping.')
            continue

        proxy.FileNames = new_files
        proxy.UpdatePipeline()
        label = proxy.GetXMLLabel() or pattern
        print(f'[{{_SIM}}] Reloaded {{label}}: {{len(new_files)}} file(s) '
              f'({{os.path.basename(new_files[0])}} … {{os.path.basename(new_files[-1])}})')
        reloaded += 1

    if reloaded == 0:
        print(f'[{{_SIM}}] No VTK readers updated. '
              'If the pipeline is empty, run visualize.py first.')
    else:
        GetAnimationScene().UpdateAnimationUsingDataTimeSteps()
        Render()
        print(f'[{{_SIM}}] Done — {{reloaded}} reader(s) refreshed.')

except Exception as e:
    print(f'[{{_SIM}}] Reload failed: {{e}}')
    raise
"#).unwrap();

    println!("wrote {}", path);
}

// ------------------------------------------------------------
// VTK reader — mesh + per-cell velocity and pressure
// ------------------------------------------------------------

struct StokesField {
    vx: Vec<f64>,
    vy: Vec<f64>,
    t0: Vec<usize>,
    t1: Vec<usize>,
    t2: Vec<usize>,
    vel_x:    Vec<f64>,
    vel_y:    Vec<f64>,
    pressure: Vec<f64>,
}

fn read_vtk_2d(path: &str) -> StokesField {
    let text  = std::fs::read_to_string(path).expect("failed to read VTK file");
    let lines: Vec<&str> = text.lines().map(str::trim).collect();

    let pi       = lines.iter().position(|l| l.starts_with("POINTS")).unwrap();
    let n_points: usize = lines[pi].split_whitespace().nth(1).unwrap().parse().unwrap();
    let mut vx = Vec::with_capacity(n_points);
    let mut vy = Vec::with_capacity(n_points);
    for k in 0..n_points {
        let mut it = lines[pi + 1 + k].split_whitespace();
        vx.push(it.next().unwrap().parse::<f64>().unwrap());
        vy.push(it.next().unwrap().parse::<f64>().unwrap());
    }

    let ci      = lines.iter().position(|l| l.starts_with("CELLS")).unwrap();
    let n_cells: usize = lines[ci].split_whitespace().nth(1).unwrap().parse().unwrap();
    let mut t0 = Vec::with_capacity(n_cells);
    let mut t1 = Vec::with_capacity(n_cells);
    let mut t2 = Vec::with_capacity(n_cells);
    for k in 0..n_cells {
        let mut it = lines[ci + 1 + k].split_whitespace();
        assert_eq!(it.next().unwrap(), "3", "expected triangles");
        t0.push(it.next().unwrap().parse::<usize>().unwrap());
        t1.push(it.next().unwrap().parse::<usize>().unwrap());
        t2.push(it.next().unwrap().parse::<usize>().unwrap());
    }

    let vi = lines.iter().position(|l| l.starts_with("velocity")).unwrap();
    let mut vel_x = Vec::with_capacity(n_cells);
    let mut vel_y = Vec::with_capacity(n_cells);
    for k in 0..n_cells {
        let mut it = lines[vi + 1 + k].split_whitespace();
        vel_x.push(it.next().unwrap().parse::<f64>().unwrap());
        vel_y.push(it.next().unwrap().parse::<f64>().unwrap());
    }

    let pri = lines.iter().position(|l| l.starts_with("pressure")).unwrap();
    let pressure: Vec<f64> = (0..n_cells)
        .map(|k| lines[pri + 1 + k].parse().unwrap())
        .collect();

    StokesField { vx, vy, t0, t1, t2, vel_x, vel_y, pressure }
}

// ------------------------------------------------------------
// Filtered mesh — subset of triangles and reindexed vertices
// ------------------------------------------------------------

struct FilteredMesh {
    vx:       Vec<f64>,
    vy:       Vec<f64>,
    t0:       Vec<usize>,
    t1:       Vec<usize>,
    t2:       Vec<usize>,
    vel_x:    Vec<f64>,
    vel_y:    Vec<f64>,
    pressure: Vec<f64>,
}

/// Find the body bounding box by locating boundary edges (edges belonging to
/// exactly one triangle) whose vertices are NOT on the outer domain boundary.
fn find_body_bounds(field: &StokesField) -> (f64, f64, f64, f64) {
    use std::collections::HashMap;

    let dom_x_min = field.vx.iter().cloned().fold(f64::INFINITY,     f64::min);
    let dom_x_max = field.vx.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let dom_y_min = field.vy.iter().cloned().fold(f64::INFINITY,     f64::min);
    let dom_y_max = field.vy.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let tol = 5.0;

    let mut edge_count: HashMap<(usize, usize), u32> = HashMap::new();
    for k in 0..field.t0.len() {
        for &(a, b) in &[
            (field.t0[k], field.t1[k]),
            (field.t1[k], field.t2[k]),
            (field.t2[k], field.t0[k]),
        ] {
            *edge_count.entry((a.min(b), a.max(b))).or_insert(0) += 1;
        }
    }

    let mut bx_min = f64::INFINITY;
    let mut bx_max = f64::NEG_INFINITY;
    let mut by_min = f64::INFINITY;
    let mut by_max = f64::NEG_INFINITY;

    for (&(a, b), &cnt) in &edge_count {
        if cnt != 1 { continue; }
        for &node in &[a, b] {
            let x = field.vx[node];
            let y = field.vy[node];
            // Skip nodes on the outer domain boundary
            if y < dom_y_min + tol || y > dom_y_max - tol
            || x < dom_x_min + tol || x > dom_x_max - tol {
                continue;
            }
            bx_min = bx_min.min(x);
            bx_max = bx_max.max(x);
            by_min = by_min.min(y);
            by_max = by_max.max(y);
        }
    }

    (bx_min, bx_max, by_min, by_max)
}

/// Extract triangles whose centroid is within [x_lo, x_hi] × [y_lo, y_hi], reindex vertices.
fn filter_mesh(field: &StokesField, x_lo: f64, x_hi: f64, y_lo: f64, y_hi: f64) -> FilteredMesh {
    let n_all = field.t0.len();
    let mut tri_sel: Vec<usize> = Vec::new();
    for k in 0..n_all {
        let inside = |n: usize| {
            field.vx[n] >= x_lo && field.vx[n] <= x_hi
            && field.vy[n] >= y_lo && field.vy[n] <= y_hi
        };
        if inside(field.t0[k]) && inside(field.t1[k]) && inside(field.t2[k]) {
            tri_sel.push(k);
        }
    }

    let mut used: std::collections::HashSet<usize> = std::collections::HashSet::new();
    for &k in &tri_sel {
        used.insert(field.t0[k]);
        used.insert(field.t1[k]);
        used.insert(field.t2[k]);
    }
    let mut used_sorted: Vec<usize> = used.into_iter().collect();
    used_sorted.sort_unstable();

    let mut remap = vec![0usize; field.vx.len()];
    for (new_idx, &old_idx) in used_sorted.iter().enumerate() {
        remap[old_idx] = new_idx;
    }

    let vx:  Vec<f64> = used_sorted.iter().map(|&i| field.vx[i]).collect();
    let vy:  Vec<f64> = used_sorted.iter().map(|&i| field.vy[i]).collect();
    let t0:  Vec<usize> = tri_sel.iter().map(|&k| remap[field.t0[k]]).collect();
    let t1:  Vec<usize> = tri_sel.iter().map(|&k| remap[field.t1[k]]).collect();
    let t2:  Vec<usize> = tri_sel.iter().map(|&k| remap[field.t2[k]]).collect();
    let vel_x:    Vec<f64> = tri_sel.iter().map(|&k| field.vel_x[k]).collect();
    let vel_y:    Vec<f64> = tri_sel.iter().map(|&k| field.vel_y[k]).collect();
    let pressure: Vec<f64> = tri_sel.iter().map(|&k| field.pressure[k]).collect();

    FilteredMesh { vx, vy, t0, t1, t2, vel_x, vel_y, pressure }
}

fn write_vtk_submesh(path: &str, fmesh: &FilteredMesh) {
    let n_pts   = fmesh.vx.len();
    let n_cells = fmesh.t0.len();

    let mut f = std::fs::File::create(path).unwrap();
    writeln!(f, "# vtk DataFile Version 2.0").unwrap();
    writeln!(f, "Acoustic mesh under study").unwrap();
    writeln!(f, "ASCII").unwrap();
    writeln!(f, "DATASET UNSTRUCTURED_GRID").unwrap();

    writeln!(f, "POINTS {} double", n_pts).unwrap();
    for i in 0..n_pts {
        writeln!(f, "{:.9} {:.9} 0.0", fmesh.vx[i], fmesh.vy[i]).unwrap();
    }

    writeln!(f, "CELLS {} {}", n_cells, n_cells * 4).unwrap();
    for i in 0..n_cells {
        writeln!(f, "3 {} {} {}", fmesh.t0[i], fmesh.t1[i], fmesh.t2[i]).unwrap();
    }

    writeln!(f, "CELL_TYPES {}", n_cells).unwrap();
    for _ in 0..n_cells { writeln!(f, "5").unwrap(); }

    writeln!(f, "CELL_DATA {}", n_cells).unwrap();
    writeln!(f, "SCALARS pressure double 1").unwrap();
    writeln!(f, "LOOKUP_TABLE default").unwrap();
    for i in 0..n_cells { writeln!(f, "{:.9e}", fmesh.pressure[i]).unwrap(); }
    writeln!(f, "VECTORS velocity double").unwrap();
    for i in 0..n_cells {
        writeln!(f, "{:.9e} {:.9e} 0.0", fmesh.vel_x[i], fmesh.vel_y[i]).unwrap();
    }

    println!("wrote {} ({} points, {} triangles)", path, n_pts, n_cells);
}

// ------------------------------------------------------------
// VTK particle snapshot writer
// ------------------------------------------------------------

fn write_vtk_particles(
    path:     &str,
    step:     usize,
    px:       &[f64],
    py:       &[f64],
    vel_x:    &[f64],
    vel_y:    &[f64],
    pressure: &[f64],
) {
    let n = px.len();
    let mut f = std::fs::File::create(path).unwrap();

    writeln!(f, "# vtk DataFile Version 2.0").unwrap();
    writeln!(f, "Particles step {}", step).unwrap();
    writeln!(f, "ASCII").unwrap();
    writeln!(f, "DATASET POLYDATA").unwrap();
    writeln!(f, "POINTS {} double", n).unwrap();
    for i in 0..n {
        writeln!(f, "{:.9} {:.9} 0.0", px[i], py[i]).unwrap();
    }

    // VERTICES so tools like ParaView render them as points
    writeln!(f, "VERTICES {} {}", n, 2 * n).unwrap();
    for i in 0..n {
        writeln!(f, "1 {}", i).unwrap();
    }

    writeln!(f, "POINT_DATA {}", n).unwrap();

    writeln!(f, "SCALARS pressure double 1").unwrap();
    writeln!(f, "LOOKUP_TABLE default").unwrap();
    for i in 0..n {
        writeln!(f, "{:.9e}", pressure[i]).unwrap();
    }

    writeln!(f, "VECTORS velocity double").unwrap();
    for i in 0..n {
        writeln!(f, "{:.9e} {:.9e} 0.0", vel_x[i], vel_y[i]).unwrap();
    }
}

// ------------------------------------------------------------
// Main
// ------------------------------------------------------------

fn main() {
    let args  = parse_args();
    let path  = "examples/acoustic_field.vtk";
    let field = read_vtk_2d(path);
    println!("mesh: {} points, {} triangles", field.vx.len(), field.t0.len());

    // Detect body bounding box from internal boundary edges
    print!("detecting body bounds... ");
    let (bx_lo, bx_hi, by_lo, by_hi) = find_body_bounds(&field);
    let body_width = bx_hi - bx_lo;
    println!("body x=[{:.1}, {:.1}]  y=[{:.1}, {:.1}]  width={:.1}",
             bx_lo, bx_hi, by_lo, by_hi, body_width);

    let body_height = by_hi - by_lo;

    // Particle region: strictly in front of the body (upstream, x > bx_hi).
    let p_x_lo = bx_hi;
    let p_x_hi = bx_hi + args.x_margin * body_width;
    let p_y_lo = by_lo - args.y_margin * body_height;
    let p_y_hi = by_hi + args.y_margin * body_height;
    println!("particle region: x=[{:.1}, {:.1}]  y=[{:.1}, {:.1}]",
             p_x_lo, p_x_hi, p_y_lo, p_y_hi);

    // Mesh region: particle extent + configurable margin on all sides.
    // Also always includes the body itself on the left.
    let x_lo = (bx_lo - args.mesh_x_margin * body_width).min(bx_lo - body_width);
    let x_hi = p_x_hi + args.mesh_x_margin * body_width;
    let y_lo = p_y_lo - args.mesh_y_margin * body_height;
    let y_hi = p_y_hi + args.mesh_y_margin * body_height;
    println!("mesh region:     x=[{:.1}, {:.1}]  y=[{:.1}, {:.1}]", x_lo, x_hi, y_lo, y_hi);

    std::fs::create_dir_all("vtk_out").unwrap();

    let fmesh = filter_mesh(&field, x_lo, x_hi, y_lo, y_hi);
    let sub_y_min = fmesh.vy.iter().cloned().fold(f64::INFINITY,     f64::min);
    let sub_y_max = fmesh.vy.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    println!("filtered mesh: {} points, {} triangles  x=[{:.1},{:.1}] y=[{:.1},{:.1}]",
             fmesh.vx.len(), fmesh.t0.len(), x_lo, x_hi, sub_y_min, sub_y_max);

    write_vtk_submesh("vtk_out/acoustic_mesh_under_study.vtk", &fmesh);

    // Use the FULL mesh for locator/advector so particles always find a valid
    // cell regardless of where periodicity wraps them to.
    let full_mesh = TriMesh {
        vx: &field.vx, vy: &field.vy,
        t0: &field.t0, t1: &field.t1, t2: &field.t2,
    };

    let mut locator  = Locator2D::new(&full_mesh).unwrap();
    let mut advector = ParticleAdvector2D::new(
        locator.stream.clone(),
        &field.vel_x, &field.vel_y, &field.pressure,
    ).unwrap();

    // Particle grid: uniform grid in front of the body.
    // Spacing: use --spacing directly if given, otherwise derive from --ppc.
    let spacing = args.spacing.unwrap_or(body_width / args.ppc as f64);
    let p_x_lo = p_x_lo.max(x_lo);
    let p_x_hi = p_x_hi.min(x_hi);
    let p_y_lo = p_y_lo.max(sub_y_min);
    let p_y_hi = p_y_hi.min(sub_y_max);
    let nx = ((p_x_hi - p_x_lo) / spacing).ceil() as usize;
    let ny = ((p_y_hi - p_y_lo) / spacing).ceil() as usize;
    let n_actual = nx * ny;
    println!("particle grid: {}×{}={} (spacing={:.2})  x=[{:.1},{:.1}] y=[{:.1},{:.1}]",
             nx, ny, n_actual, spacing, p_x_lo, p_x_hi, p_y_lo, p_y_hi);

    let mut qx_init = Vec::with_capacity(n_actual);
    let mut qy_init = Vec::with_capacity(n_actual);
    for ix in 0..nx {
        let x = p_x_lo + (ix as f64 + 0.5) * spacing;
        for iy in 0..ny {
            let y = p_y_lo + (iy as f64 + 0.5) * spacing;
            qx_init.push(x);
            qy_init.push(y);
        }
    }

    let mut px_d  = locator.stream.clone_htod(&qx_init).unwrap();
    let mut py_d  = locator.stream.clone_htod(&qy_init).unwrap();
    let mut ids_d = locator.stream.alloc_zeros::<i32>(n_actual).unwrap();

    // CPU scratch for I/O
    let mut px_h  = vec![0f64; n_actual];
    let mut py_h  = vec![0f64; n_actual];
    let mut u_h   = vec![0f64; n_actual];
    let mut v_h   = vec![0f64; n_actual];
    let mut p_h   = vec![0f64; n_actual];
    let mut ids_h = vec![-1i32; n_actual];

    // path to submesh VTK relative to vtk_out/ (where pvpython will be run)
    write_visualize_py("vtk_out", "acoustic_mesh_under_study.vtk", n_actual);
    write_reload_macro_py("vtk_out");

    println!("\nsteps={} out_every={} dt={}", args.steps, args.out_every, args.dt);

    for step in 0..=args.steps {
        // locate → gather
        locator.locate(&px_d, &py_d, &mut ids_d).unwrap();
        advector.gather(&ids_d).unwrap();

        // output snapshot
        if step % args.out_every == 0 {
            locator.stream.memcpy_dtoh(&px_d,           &mut px_h).unwrap();
            locator.stream.memcpy_dtoh(&py_d,           &mut py_h).unwrap();
            locator.stream.memcpy_dtoh(&advector.vel_x, &mut u_h).unwrap();
            locator.stream.memcpy_dtoh(&advector.vel_y, &mut v_h).unwrap();
            locator.stream.memcpy_dtoh(&advector.pressure, &mut p_h).unwrap();
            locator.stream.memcpy_dtoh(&ids_d,          &mut ids_h).unwrap();

            let vtk_path = format!("vtk_out/particles_{:06}.vtk", step);
            write_vtk_particles(&vtk_path, step, &px_h, &py_h, &u_h, &v_h, &p_h);
            println!("step {:>6}  px[0]={:.4}  py[0]={:.4}  tri[0]={}  p[0]={:.4}  → {}",
                step, px_h[0], py_h[0], ids_h[0], p_h[0], vtk_path);
        }

        if step < args.steps {
            advector.advect(&mut px_d, &mut py_d, args.dt).unwrap();
            advector.apply_periodicity(
                &mut px_d, &mut py_d,
                x_lo, x_hi, sub_y_min, sub_y_max,
            ).unwrap();
        }
    }
}
