use jaali_clow::locator::{Locator2D, ParticleAdvector2D};
use jaali_clow::mesh::TriMesh;
use std::io::Write;

// ------------------------------------------------------------
// CLI
// ------------------------------------------------------------

struct Args {
    steps:     usize,
    out_every: usize,
    dt:        f64,
    particles: usize,
    seed:      u64,
}

fn parse_args() -> Args {
    let raw: Vec<String> = std::env::args().collect();
    let mut steps     = 100usize;
    let mut out_every = 10usize;
    let mut dt        = 0.1f64;
    let mut particles = 4usize;
    let mut seed      = 42u64;
    let mut i = 1;
    while i < raw.len() {
        match raw[i].as_str() {
            "--steps"     => { steps     = raw[i+1].parse().unwrap(); i += 2; }
            "--out-every" => { out_every = raw[i+1].parse().unwrap(); i += 2; }
            "--dt"        => { dt        = raw[i+1].parse().unwrap(); i += 2; }
            "--particles" => { particles = raw[i+1].parse().unwrap(); i += 2; }
            "--seed"      => { seed      = raw[i+1].parse().unwrap(); i += 2; }
            _ => { i += 1; }
        }
    }
    Args { steps, out_every, dt, particles, seed }
}

// ------------------------------------------------------------
// Minimal xorshift64 PRNG (no external crate needed)
// ------------------------------------------------------------

struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self { Self(seed.max(1)) }

    fn next_u64(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }

    /// Uniform f64 in [0, 1)
    fn next_f64(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }

    /// Uniform f64 in [lo, hi)
    fn uniform(&mut self, lo: f64, hi: f64) -> f64 {
        lo + self.next_f64() * (hi - lo)
    }
}

// ------------------------------------------------------------
// ParaView visualisation script generator
// ------------------------------------------------------------

fn write_visualize_py(out_dir: &str, field_vtk_rel: &str, n_particles: usize) {
    let path = format!("{}/visualize.py", out_dir);
    let mut f = std::fs::File::create(&path).unwrap();

    write!(f, r#"# Auto-generated by jaali_clow::examples::particles_in_stokes_2d
# Run from the "{out_dir}" directory:
#   pvpython visualize.py
#
# Simulation: Stokes 2D — {n_particles} particles

from paraview.simple import *
import glob, re

paraview.simple._DisableFirstRenderCameraReset()

_SIM = "Stokes 2D — {n_particles} particles"

# ── Background Stokes field ──────────────────────────────────
field_reader = LegacyVTKReader(
    registrationName='stokes_field',
    FileNames=['{field_vtk_rel}'])
field_reader.UpdatePipeline()

view = GetActiveViewOrCreate('RenderView')

field_disp = Show(field_reader, view, 'UnstructuredGridRepresentation')
field_disp.SetRepresentationType('Surface')
ColorBy(field_disp, ('CELLS', 'velocity'))
lut_field = GetColorTransferFunction('velocity')
lut_field.VectorMode = 'Magnitude'
field_disp.RescaleTransferFunctionToDataRange(False, True)
lut_field.ApplyPreset('Cool to Warm', True)
field_disp.SetScalarBarVisibility(view, True)

bar_field = GetScalarBar(lut_field, view)
bar_field.Orientation        = 'Horizontal'
bar_field.WindowLocation     = 'Any Location'
bar_field.Position           = [0.25, 0.10]
bar_field.ScalarBarLength    = 0.50
bar_field.ScalarBarThickness = 16
bar_field.Title              = 'velocity magnitude (field)'

# ── Particle animation ───────────────────────────────────────
p_files = sorted(
    glob.glob('particles_*.vtk'),
    key=lambda f: int(re.search(r'\d+', f).group()))
if not p_files:
    raise RuntimeError(
        'No particles_*.vtk found. Run the simulation first, '
        'then launch pvpython from the vtk_out directory.')
print(f'[{{_SIM}}] {{len(p_files)}} timestep(s): {{p_files[0]}} ... {{p_files[-1]}}')

p_reader = LegacyVTKReader(registrationName='particles', FileNames=p_files)
p_reader.UpdatePipeline()

GetAnimationScene().UpdateAnimationUsingDataTimeSteps()

p_disp = Show(p_reader, view, 'UnstructuredGridRepresentation')
p_disp.SetRepresentationType('Point Gaussian')
p_disp.GaussianRadius   = 0.02
p_disp.ScaleByArray     = 0
p_disp.UseScaleFunction = 0
ColorBy(p_disp, ('POINTS', 'pressure'))
lut_p = GetColorTransferFunction('pressure')
p_disp.RescaleTransferFunctionToDataRangeOverTime()
lut_p.ApplyPreset('Plasma (matplotlib)', True)
p_disp.SetScalarBarVisibility(view, True)

bar_p = GetScalarBar(lut_p, view)
bar_p.Orientation        = 'Horizontal'
bar_p.WindowLocation     = 'Any Location'
bar_p.Position           = [0.25, 0.02]
bar_p.ScalarBarLength    = 0.50
bar_p.ScalarBarThickness = 16
bar_p.Title              = 'pressure (particles)'

# ── Camera — look down Z at the 2-D plane ────────────────────
_b  = field_reader.GetDataInformation().GetBounds()
_cx = 0.5 * (_b[0] + _b[1])
_cy = 0.5 * (_b[2] + _b[3])
_sp = max(_b[1] - _b[0], _b[3] - _b[2]) * 0.75

view.CameraPosition   = [_cx, _cy, _sp * 3.0]
view.CameraFocalPoint = [_cx, _cy, 0.0]
view.CameraViewUp     = [0.0, 1.0, 0.0]
view.ResetCamera()
Render()
print(f'[{{_SIM}}] visualization ready.')
"#,
        out_dir = out_dir,
        field_vtk_rel = field_vtk_rel,
        n_particles = n_particles,
    ).unwrap();

    println!("wrote {}", path);
}

// ------------------------------------------------------------
// ParaView reload macro generator
// ------------------------------------------------------------

fn write_reload_macro_py(out_dir: &str) {
    let path = format!("{}/reload_macro.py", out_dir);
    let mut f = std::fs::File::create(&path).unwrap();

    write!(f, r#""""
jaali_clow — ParaView reload macro
====================================

Add this file as a ParaView macro once:
    Tools > Macros > Add New Macro > (select this file)

Then trigger it whenever you want to pick up newly written VTK files:
    Macros > reload_macro          (menu)
    Tools > Keyboard Shortcuts     (assign a key, ParaView 5.12+)

What it does
------------
1. Finds every LegacyVTKReader currently loaded in the pipeline.
2. Derives the glob pattern from the first file in each reader's list
   (e.g. particles_000000.vtk → particles_*.vtk).
3. Re-scans the same directory, sorts numerically, skips empty/corrupt
   files, and updates each reader.
4. Refreshes the animation timeline and re-renders.
""""

from paraview.simple import *
import glob, os, re

# ── Reader XML names for legacy VTK across ParaView versions ─
_VTK_READER_NAMES = {{
    'LegacyVTKReader',
    'PVLegacyVTKFileReader',
    'legacyVTKReader',
}}

_SIM = "jaali_clow Stokes 2D"


def _is_vtk_reader(proxy):
    if proxy.GetXMLName() in _VTK_READER_NAMES:
        return True
    try:
        files = list(proxy.FileNames)
        return bool(files) and files[0].endswith('.vtk')
    except Exception:
        return False


def _is_valid_vtk(filepath):
    """Reject zero-byte or missing files."""
    try:
        return os.path.getsize(filepath) > 0
    except OSError:
        return False


def _sorted_valid_vtk(pattern):
    files = glob.glob(pattern)
    files.sort(key=lambda f: int(re.search(r'\d+', os.path.basename(f)).group()))
    valid = []
    for fp in files:
        if _is_valid_vtk(fp):
            valid.append(fp)
        else:
            print(f'[{{_SIM}}] WARNING: skipping empty/corrupt file {{fp}}')
    return valid


def _make_pattern(filepath):
    """
    Derive an absolute glob pattern from one existing file path.
    particles_000000.vtk  →  <dir>/particles_*.vtk
    """
    abspath   = os.path.abspath(filepath)
    directory = os.path.dirname(abspath)
    basename  = os.path.basename(abspath)
    m = re.match(r'^(.*?)_\d+\.vtk$', basename)
    if m is None:
        return None
    return os.path.join(directory, f'{{m.group(1)}}_*.vtk')


try:
    sources = GetSources()
    if not sources:
        print(f'[{{_SIM}}] Pipeline is empty — run visualize.py first '
              '(File > Run Script or Tools > Python Shell).')
    else:
        print(f'[{{_SIM}}] Pipeline has {{len(sources)}} source(s):')
        for (name, _), proxy in sources.items():
            print(f'          {{name!r}}  XML={{proxy.GetXMLName()!r}}')

    reloaded = 0

    for proxy in sources.values():
        if not _is_vtk_reader(proxy):
            continue

        try:
            current_files = list(proxy.FileNames)
        except Exception:
            continue

        if not current_files:
            continue

        pattern = _make_pattern(current_files[0])
        if pattern is None:
            print(f'[{{_SIM}}] Cannot derive pattern from {{current_files[0]!r}} — skipping.')
            continue

        print(f'[{{_SIM}}] Scanning: {{pattern}}')
        new_files = _sorted_valid_vtk(pattern)

        if not new_files:
            print(f'[{{_SIM}}] No files matched — skipping.')
            continue

        proxy.FileNames = new_files
        proxy.UpdatePipeline()
        label = proxy.GetXMLLabel() or pattern
        print(f'[{{_SIM}}] Reloaded {{label}}: {{len(new_files)}} file(s) '
              f'({{os.path.basename(new_files[0])}} … {{os.path.basename(new_files[-1])}})')
        reloaded += 1

    if reloaded == 0:
        print(f'[{{_SIM}}] No VTK readers updated. '
              'If the pipeline is empty, run visualize.py first.')
    else:
        GetAnimationScene().UpdateAnimationUsingDataTimeSteps()
        Render()
        print(f'[{{_SIM}}] Done — {{reloaded}} reader(s) refreshed.')

except Exception as e:
    print(f'[{{_SIM}}] Reload failed: {{e}}')
    raise
"#).unwrap();

    println!("wrote {}", path);
}

// ------------------------------------------------------------
// VTK reader — mesh + per-cell velocity and pressure
// ------------------------------------------------------------

struct StokesField {
    vx: Vec<f64>,
    vy: Vec<f64>,
    t0: Vec<usize>,
    t1: Vec<usize>,
    t2: Vec<usize>,
    vel_x:    Vec<f64>,
    vel_y:    Vec<f64>,
    pressure: Vec<f64>,
}

fn read_vtk_2d(path: &str) -> StokesField {
    let text  = std::fs::read_to_string(path).expect("failed to read VTK file");
    let lines: Vec<&str> = text.lines().map(str::trim).collect();

    let pi       = lines.iter().position(|l| l.starts_with("POINTS")).unwrap();
    let n_points: usize = lines[pi].split_whitespace().nth(1).unwrap().parse().unwrap();
    let mut vx = Vec::with_capacity(n_points);
    let mut vy = Vec::with_capacity(n_points);
    for k in 0..n_points {
        let mut it = lines[pi + 1 + k].split_whitespace();
        vx.push(it.next().unwrap().parse::<f64>().unwrap());
        vy.push(it.next().unwrap().parse::<f64>().unwrap());
    }

    let ci      = lines.iter().position(|l| l.starts_with("CELLS")).unwrap();
    let n_cells: usize = lines[ci].split_whitespace().nth(1).unwrap().parse().unwrap();
    let mut t0 = Vec::with_capacity(n_cells);
    let mut t1 = Vec::with_capacity(n_cells);
    let mut t2 = Vec::with_capacity(n_cells);
    for k in 0..n_cells {
        let mut it = lines[ci + 1 + k].split_whitespace();
        assert_eq!(it.next().unwrap(), "3", "expected triangles");
        t0.push(it.next().unwrap().parse::<usize>().unwrap());
        t1.push(it.next().unwrap().parse::<usize>().unwrap());
        t2.push(it.next().unwrap().parse::<usize>().unwrap());
    }

    let vi = lines.iter().position(|l| l.starts_with("velocity")).unwrap();
    let mut vel_x = Vec::with_capacity(n_cells);
    let mut vel_y = Vec::with_capacity(n_cells);
    for k in 0..n_cells {
        let mut it = lines[vi + 1 + k].split_whitespace();
        vel_x.push(it.next().unwrap().parse::<f64>().unwrap());
        vel_y.push(it.next().unwrap().parse::<f64>().unwrap());
    }

    let pri = lines.iter().position(|l| l.starts_with("pressure")).unwrap();
    let pressure: Vec<f64> = (0..n_cells)
        .map(|k| lines[pri + 1 + k].parse().unwrap())
        .collect();

    StokesField { vx, vy, t0, t1, t2, vel_x, vel_y, pressure }
}

// ------------------------------------------------------------
// VTK particle snapshot writer
// ------------------------------------------------------------

fn write_vtk_particles(
    path:     &str,
    step:     usize,
    px:       &[f64],
    py:       &[f64],
    vel_x:    &[f64],
    vel_y:    &[f64],
    pressure: &[f64],
) {
    let n = px.len();
    let mut f = std::fs::File::create(path).unwrap();

    writeln!(f, "# vtk DataFile Version 2.0").unwrap();
    writeln!(f, "Particles step {}", step).unwrap();
    writeln!(f, "ASCII").unwrap();
    writeln!(f, "DATASET POLYDATA").unwrap();
    writeln!(f, "POINTS {} double", n).unwrap();
    for i in 0..n {
        writeln!(f, "{:.9} {:.9} 0.0", px[i], py[i]).unwrap();
    }

    // VERTICES so tools like ParaView render them as points
    writeln!(f, "VERTICES {} {}", n, 2 * n).unwrap();
    for i in 0..n {
        writeln!(f, "1 {}", i).unwrap();
    }

    writeln!(f, "POINT_DATA {}", n).unwrap();

    writeln!(f, "SCALARS pressure double 1").unwrap();
    writeln!(f, "LOOKUP_TABLE default").unwrap();
    for i in 0..n {
        writeln!(f, "{:.9e}", pressure[i]).unwrap();
    }

    writeln!(f, "VECTORS velocity double").unwrap();
    for i in 0..n {
        writeln!(f, "{:.9e} {:.9e} 0.0", vel_x[i], vel_y[i]).unwrap();
    }
}

// ------------------------------------------------------------
// Main
// ------------------------------------------------------------

fn main() {
    let args  = parse_args();
    let path  = "examples/stokes_field_2d.vtk";
    let field = read_vtk_2d(path);
    println!("mesh: {} points, {} triangles", field.vx.len(), field.t0.len());

    // Mesh bounding box for periodicity
    let x_min = field.vx.iter().cloned().fold(f64::INFINITY,  f64::min);
    let x_max = field.vx.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let y_min = field.vy.iter().cloned().fold(f64::INFINITY,  f64::min);
    let y_max = field.vy.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    println!("domain: x=[{:.4}, {:.4}]  y=[{:.4}, {:.4}]", x_min, x_max, y_min, y_max);

    let mesh = TriMesh {
        vx: &field.vx, vy: &field.vy,
        t0: &field.t0, t1: &field.t1, t2: &field.t2,
    };

    let mut locator  = Locator2D::new(&mesh).unwrap();
    let mut advector = ParticleAdvector2D::new(
        locator.stream.clone(),
        &field.vel_x, &field.vel_y, &field.pressure,
    ).unwrap();

    // Initial particle positions — random inside mesh bbox
    let n = args.particles;
    let mut rng = Rng::new(args.seed);
    let qx_init: Vec<f64> = (0..n).map(|_| rng.uniform(x_min, x_max)).collect();
    let qy_init: Vec<f64> = (0..n).map(|_| rng.uniform(y_min, y_max)).collect();
    println!("particles={} seed={}", n, args.seed);

    let mut px_d  = locator.stream.clone_htod(&qx_init).unwrap();
    let mut py_d  = locator.stream.clone_htod(&qy_init).unwrap();
    let mut ids_d = locator.stream.alloc_zeros::<i32>(n).unwrap();

    // CPU scratch for I/O
    let mut px_h  = vec![0f64; n];
    let mut py_h  = vec![0f64; n];
    let mut u_h   = vec![0f64; n];
    let mut v_h   = vec![0f64; n];
    let mut p_h   = vec![0f64; n];
    let mut ids_h = vec![-1i32; n];

    std::fs::create_dir_all("vtk_out").unwrap();
    // path to field VTK relative to vtk_out/ (where pvpython will be run)
    write_visualize_py("vtk_out", "../examples/stokes_field_2d.vtk", n);
    write_reload_macro_py("vtk_out");

    println!("\nsteps={} out_every={} dt={}", args.steps, args.out_every, args.dt);

    for step in 0..=args.steps {
        // locate → gather
        locator.locate(&px_d, &py_d, &mut ids_d).unwrap();
        advector.gather(&ids_d).unwrap();

        // output snapshot
        if step % args.out_every == 0 {
            locator.stream.memcpy_dtoh(&px_d,           &mut px_h).unwrap();
            locator.stream.memcpy_dtoh(&py_d,           &mut py_h).unwrap();
            locator.stream.memcpy_dtoh(&advector.vel_x, &mut u_h).unwrap();
            locator.stream.memcpy_dtoh(&advector.vel_y, &mut v_h).unwrap();
            locator.stream.memcpy_dtoh(&advector.pressure, &mut p_h).unwrap();
            locator.stream.memcpy_dtoh(&ids_d,          &mut ids_h).unwrap();

            let vtk_path = format!("vtk_out/particles_{:06}.vtk", step);
            write_vtk_particles(&vtk_path, step, &px_h, &py_h, &u_h, &v_h, &p_h);
            println!("step {:>6}  px[0]={:.4}  py[0]={:.4}  tri[0]={}  p[0]={:.4}  → {}",
                step, px_h[0], py_h[0], ids_h[0], p_h[0], vtk_path);
        }

        if step < args.steps {
            advector.advect(&mut px_d, &mut py_d, args.dt).unwrap();
            advector.apply_periodicity(
                &mut px_d, &mut py_d,
                x_min, x_max, y_min, y_max,
            ).unwrap();
        }
    }
}
